deployment:
  tasks:
    - echo "Starting deployment..."

    - export DEPLOYPATH=/home/lrolrlgh/ivac-appointment-system

    # Navigate to the project directory (change to your project directory)
    # - cd /path/to/your/nextjs/project

    # Install dependencies (optional: if not already done)
    - npm install

    # Build the Next.js project
    - npm run build

    # Copy the `.next` build folder to the deployment path
    - /bin/cp -r .next $DEPLOYPATH

    # Copy the necessary static files (public directory) to the deployment path
    - /bin/cp -r public $DEPLOYPATH

    # Copy the Next.js server files to handle SSR (server-side rendering) and API routes
    - /bin/cp -r server $DEPLOYPATH

    # Ensure the right permissions are set (optional, depends on server)
    - chmod -R 755 $DEPLOYPATH

    - echo "Deployment complete!"
