import type { Metadata } from "next";
import { Suspense } from "react";
import { LinearProgress } from "@mui/material";

export const metadata: Metadata = {
  title: "Visa Service | Login",
  description: "Generated by create next app",
};

export default function PageLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <Suspense fallback={<LinearProgress />}>{children}</Suspense>;
}
